# Generated by Django 6.0.7 on 2026-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('gratuito', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
