# Generated by Django 6.0.7 on 2026-07-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(default='Brasília', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='evento',
            name='fonte',
            field=models.CharField(default='sympla', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='id_externo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_ingressos',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_original',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='preco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=300),
        ),
    ]
