# Generated by Django 6.1 on 2026-08-26 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_ingresso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas quando o evento foi cadastrado por um usuário do site (não pelo scraper).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=10),
        ),
    ]
