# Generated by Django 6.0.7 on 2026-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_busca_postgres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='resumo',
            field=models.CharField(blank=True, max_length=200, verbose_name='resumo'),
        ),
    ]
