# Generated by Django 6.0.8 on 2026-09-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_criptografar_token_sympla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegracaoSympla',
        ),
    ]
