# Generated by Django 6.0.8 on 2026-09-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_delete_integracaosympla'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='destaque_pago_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='plano_destaque',
            field=models.CharField(choices=[('normal', 'Normal'), ('destaque', 'Destaque'), ('destaque-plus', 'Destaque Plus'), ('premium', 'Premium')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('normal', 'Normal'), ('destaque', 'Destaque'), ('destaque-plus', 'Destaque Plus'), ('premium', 'Premium')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('atendida_em', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_destaque', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'solicitação de destaque',
                'verbose_name_plural': 'solicitações de destaque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
