# Generated by Django 6.0.8 on 2026-09-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_evento_destaque_pago_ate_evento_plano_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagem larga, usada em destaques e banners promocionais.', upload_to='eventos/banners/%Y/%m/', verbose_name='banner'),
        ),
    ]
