# Generated by Django 6.0.8 on 2026-09-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_evento_banner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='local',
            name='eventos_loc_nomenorm_idx',
        ),
        migrations.RemoveIndex(
            model_name='produtor',
            name='eventos_pro_nomenorm_idx',
        ),
        migrations.AlterField(
            model_name='local',
            name='nome_normalizado',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='nome_normalizado',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
