# Generated by Django 6.0.8 on 2026-09-20 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_remove_local_eventos_loc_nomenorm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segredo_cifrado', models.BinaryField()),
                ('confirmado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo_totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dispositivo de autenticação em duas etapas',
                'verbose_name_plural': 'dispositivos de autenticação em duas etapas',
            },
        ),
    ]
